### PR TITLE
Remove user specific idea files

### LINKED ISSUE #52: Error messages opening Android Studio project
When I open the covidwatch-android repository as project in Android Studio, I get the following error messages in the Android Studio:

> 13.04.20
> 12:48	Load Settings
> 			Cannot load settings from file '/home/kai/Projects/covid-watch/covidwatch-android/app/Github-covidwatch-android-app.iml': File /home/kai/Projects/covid-watch/covidwatch-android/app/Github-covidwatch-android-app.iml does not exist
> 			Please correct the file content
> 12:48	Load Settings
> 			Cannot load settings from file '/home/kai/Projects/covid-watch/covidwatch-android/Github-covidwatch-android-COVIDWatch.iml': File /home/kai/Projects/covid-watch/covidwatch-android/Github-covidwatch-android-COVIDWatch.iml does not exist
> 			Please correct the file content
> 12:48	Load Settings
> 			Cannot load settings from file '/home/kai/Projects/covid-watch/covidwatch-android/.idea/CovidWatch.iml': File /home/kai/Projects/covid-watch/covidwatch-android/.idea/CovidWatch.iml does not exist
> 			Please correct the file content
> 12:48	Load Settings
> 			Cannot load settings from file '/home/kai/Projects/covid-watch/covidwatch-android/COVIDWatch.iml': File /home/kai/Projects/covid-watch/covidwatch-android/COVIDWatch.iml does not exist
> 			Please correct the file content
> 12:48	Load Settings
> 			Cannot load settings from file '/home/kai/Projects/covid-watch/covidwatch-android/covidwatch-android-COVIDWatch.iml': File /home/kai/Projects/covid-watch/covidwatch-android/covidwatch-android-COVIDWatch.iml does not exist
> 			Please correct the file content
> 12:48	Load Settings
> 			Cannot load settings from file '/home/kai/Projects/covid-watch/covidwatch-android/app/covidwatch-android-app.iml': File /home/kai/Projects/covid-watch/covidwatch-android/app/covidwatch-android-app.iml does not exist
> 			Please correct the file content
> 12:48	Load Settings
> 			Cannot load settings from file '/home/kai/Projects/covid-watch/covidwatch-android/app/app.iml': File /home/kai/Projects/covid-watch/covidwatch-android/app/app.iml does not exist
> 			Please correct the file content
> 12:48	Gradle sync started
> 12:49	* daemon not running; starting now at tcp:5037
> 12:49	* daemon started successfully
> 12:49	Unsupported Modules Detected: Compilation is not supported for following modules: COVIDWatch, CovidWatch, Github-covidwatch-android-app, Github-covidwatch-android-COVIDWatch, covidwatch-android-app, covidwatch-android-COVIDWatch, app. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.
> 12:49	Gradle sync finished in 10 s 8 ms (from cached state)

### PR DESCRIPTION
**Pull request by Apisov**
closes #52 

I deleted some files under `.idea` folder that have user-specific configurations. You would probably need to do `File->New->Import project` to refresh your `.idea` folder after you pull these changes.

### CODE REVIEW

**Review by jamesjmtaylor — APPROVED** [review]
Was able to debug on a physical Pixel device after restarting the device and selecting 'File' > 'Invalidate Caches / Restart ...' in Android Studio.

**Comment by madim** [comment]
the problem is in the master branch, where the folders are not structured properly. we might need to move all files and folders from CovidWatch to the root directory in master branch

**Comment by Apisov** [comment]
> the problem is in the master branch, where the folders are not structured properly. we might need to move all files and folders from CovidWatch to the root directory in master branch

As long as no one pushes anything to `master` we just create PR from `develop` to `master` and all good.  You can check that it doesn't have any conflicts as `develop` was branched from `master`

**Comment by nkumarcc** [comment]
This looked good to me, I'd imagine those should've been ignored anyways

**Pull request merged**
