### PR TITLE
Add crashlytics -- issue #132

### LINKED ISSUE #132: Add crashlytics to send error logs to Firebase
Will help with logging with testers

### PR DESCRIPTION
**Pull request by crayne**
Added Firebase Crashlytics support.  Tested with Crashlytics crash function and with dividing by 0. You can see the result of the tests in the Firebase Console.

### CODE REVIEW

**Review by nkumarcc — APPROVED** [review]
This lgtm, thanks for doing it so quickly! There's no user identifier type information correct? I looked at the logs and didn't see any but want to double-check.

Not sure what's up with the tests, going to glance at that before merge. Will prioritize merge though as it looks like the tests are a little iffy.

**Comment by nkumarcc** [comment]
Looks like the test fail should be resolved by this PR: #129, so merging

**Comment by nkumarcc** [comment]
Also to check my understanding, this catches all `Log.e`s right?

**Comment by crayne** [comment]
The device identifier was included when I did this for another project.  It looks like you need to set it up explicitly in the code now.  I can make another PR for it now.

**Comment by nkumarcc** [comment]
No it's better not to have it for anonymity sake

**Pull request merged**
